/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Kwarran = IDL.Record({
  'id' : IDL.Nat,
  'skDocument' : IDL.Text,
  'satgasPramukaPeduliCount' : IDL.Nat,
  'hasCampground' : IDL.Bool,
  'secretariatAddress' : IDL.Text,
  'activeSatuanKaryaCount' : IDL.Nat,
  'maleGugusdepanCount' : IDL.Nat,
  'owner' : IDL.Principal,
  'youngMembersCount' : IDL.Nat,
  'instagram' : IDL.Text,
  'name' : IDL.Text,
  'createdAt' : Time,
  'femaleGugusdepanCount' : IDL.Nat,
  'adultMembersCount' : IDL.Nat,
  'email' : IDL.Text,
  'updatedAt' : Time,
  'facebook' : IDL.Text,
  'campgroundStatus' : IDL.Text,
  'serviceTermEnd' : IDL.Text,
  'satuanKaryaNames' : IDL.Text,
  'secretariatStaffCount' : IDL.Nat,
  'hasSecretariat' : IDL.Bool,
  'serviceTermStart' : IDL.Text,
  'secretariatStatus' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addBannerImage' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createKwarran' : IDL.Func([Kwarran], [IDL.Nat], []),
  'deleteKwarran' : IDL.Func([IDL.Nat], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getKwarran' : IDL.Func([IDL.Nat], [IDL.Opt(Kwarran)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listBannerImages' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'listKwarran' : IDL.Func([], [IDL.Vec(Kwarran)], ['query']),
  'listMyKwarran' : IDL.Func([], [IDL.Vec(Kwarran)], ['query']),
  'removeBannerImage' : IDL.Func([IDL.Text], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updateKwarran' : IDL.Func([IDL.Nat, Kwarran], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Kwarran = IDL.Record({
    'id' : IDL.Nat,
    'skDocument' : IDL.Text,
    'satgasPramukaPeduliCount' : IDL.Nat,
    'hasCampground' : IDL.Bool,
    'secretariatAddress' : IDL.Text,
    'activeSatuanKaryaCount' : IDL.Nat,
    'maleGugusdepanCount' : IDL.Nat,
    'owner' : IDL.Principal,
    'youngMembersCount' : IDL.Nat,
    'instagram' : IDL.Text,
    'name' : IDL.Text,
    'createdAt' : Time,
    'femaleGugusdepanCount' : IDL.Nat,
    'adultMembersCount' : IDL.Nat,
    'email' : IDL.Text,
    'updatedAt' : Time,
    'facebook' : IDL.Text,
    'campgroundStatus' : IDL.Text,
    'serviceTermEnd' : IDL.Text,
    'satuanKaryaNames' : IDL.Text,
    'secretariatStaffCount' : IDL.Nat,
    'hasSecretariat' : IDL.Bool,
    'serviceTermStart' : IDL.Text,
    'secretariatStatus' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addBannerImage' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createKwarran' : IDL.Func([Kwarran], [IDL.Nat], []),
    'deleteKwarran' : IDL.Func([IDL.Nat], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getKwarran' : IDL.Func([IDL.Nat], [IDL.Opt(Kwarran)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listBannerImages' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'listKwarran' : IDL.Func([], [IDL.Vec(Kwarran)], ['query']),
    'listMyKwarran' : IDL.Func([], [IDL.Vec(Kwarran)], ['query']),
    'removeBannerImage' : IDL.Func([IDL.Text], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updateKwarran' : IDL.Func([IDL.Nat, Kwarran], [], []),
  });
};

export const init = ({ IDL }) => { return []; };