/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Kwarran {
  'id' : bigint,
  'skDocument' : string,
  'satgasPramukaPeduliCount' : bigint,
  'hasCampground' : boolean,
  'secretariatAddress' : string,
  'activeSatuanKaryaCount' : bigint,
  'maleGugusdepanCount' : bigint,
  'youngMembersCount' : bigint,
  'instagram' : string,
  'name' : string,
  'createdAt' : Time,
  'femaleGugusdepanCount' : bigint,
  'adultMembersCount' : bigint,
  'email' : string,
  'updatedAt' : Time,
  'facebook' : string,
  'campgroundStatus' : string,
  'serviceTermEnd' : string,
  'satuanKaryaNames' : string,
  'secretariatStaffCount' : bigint,
  'hasSecretariat' : boolean,
  'serviceTermStart' : string,
  'secretariatStatus' : string,
}
export type Time = bigint;
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createKwarran' : ActorMethod<[Kwarran], bigint>,
  'deleteKwarran' : ActorMethod<[bigint], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getKwarran' : ActorMethod<[bigint], [] | [Kwarran]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listKwarran' : ActorMethod<[], Array<Kwarran>>,
  'requestApproval' : ActorMethod<[], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updateKwarran' : ActorMethod<[bigint, Kwarran], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];